######################################################################
# Automatically generated by qmake (3.0) Fri Feb 26 16:18:39 2016
######################################################################

QT+=opengl
LIBS+=-lGLU
TEMPLATE = app
TARGET = game
INCLUDEPATH += .

# Input
HEADERS += GLPolygonWidget.h GLWindow.h
SOURCES += GLPolygonMain.cpp GLPolygonWidget.cpp GLWindow.cpp
