######################################################################
# Automatically generated by qmake (3.0) Sat May 7 22:25:46 2016
######################################################################

QT+=network
QT+=opengl
TEMPLATE = app
TARGET = client
INCLUDEPATH += .

# Input
HEADERS += ClientWindow.h
SOURCES += ClientMain.cpp ClientWindow.cpp
