######################################################################
# Automatically generated by qmake (3.0) Sat Mar 12 17:59:53 2016
######################################################################

QT+=network
QT+=opengl
TEMPLATE = app
TARGET = client
INCLUDEPATH += .

# Input
HEADERS += ClientWindow.h
SOURCES += ClientMain.cpp ClientWindow.cpp
