######################################################################
# Automatically generated by qmake (3.0) Thu Mar 10 21:07:37 2016
######################################################################

QT+=network
QT+=opengl
TEMPLATE = app
TARGET = client
INCLUDEPATH += .

# Input
HEADERS += ClientWindow.h
SOURCES += ClientMain.cpp ClientWindow.cpp
