######################################################################
# Automatically generated by qmake (3.0) Thu Mar 10 20:33:27 2016
######################################################################

QT+=network
QT+=opengl
TEMPLATE = app
TARGET = server
INCLUDEPATH += .

# Input
HEADERS += Server.h
SOURCES += Server.cpp ServerMain.cpp
