######################################################################
# Automatically generated by qmake (3.0) Sat Mar 12 18:00:09 2016
######################################################################

QT+=network
QT+=opengl
TEMPLATE = app
TARGET = server
INCLUDEPATH += .

# Input
HEADERS += Server.h
SOURCES += Server.cpp ServerMain.cpp
